version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  samurai_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samurai_api
    ports:
      - "1600:1600"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo_data: